version: "3.9"
services:
    server:
      container_name: server
      build: .
      shm_size: "2gb"
      env_file:
        - .env
      ports:
        - "80:80"

      logging:
        driver: "awslogs"
        options:
          awslogs-region: "us-west-2"
          awslogs-group: "groceryserverdocker"
          awslogs-stream: "groceryserverlogs"


