version: "3"
services:
    grocerywebcrawlerapp:
      container_name: grocerywebcrawlerapp
      build: .
      shm_size: "2gb"
      env_file:
        - .env
      ports:
        - "80:80"
        - "5000:5000"
#      logging:
#        driver: "awslogs"
#        options:
#          awslogs-region: "us-west-2"
#          awslogs-group: "log-group"
#          awslogs-stream: "log-stream"

