version: "3.9"
services:
    server:
      build:
        context: .
        dockerfile: Dockerfile
      env_file:
        - .env
      ports:
        - "3000:3000"

    grocerywebsite:
      build:
        context: grocerywebsite
        dockerfile: Dockerfile
      ports:
        - "80:80"

    cronjob:
      build:
        context: .
        dockerfile: ./cronjob/Dockerfile
      env_file:
        - .env
